version: '3.1'
services:
  calv2-demo-app:
    platform: linux/amd64
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - calv2-demo-redis
    environment:
      - REDIS_URL=redis://calv2-demo-redis:6379
  
  calv2-demo-worker:
    platform: linux/amd64
    build: 
      context: .
      dockerfile: Dockerfile    
    command: npm run dev:worker
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - calv2-demo-redis
    environment:
      - REDIS_URL=redis://calv2-demo-redis:6379
    
  calv2-demo-redis:
    platform: linux/amd64
    image: redis:6.2    
    expose:
      - 6379